### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by dude83759** [sentrionic/Valkyrie#1] opened 2021-04-05 14:02 UTC
Hello Sir, I found your clone very helpful but I want some help regarding installation, how can I contact you, please provide mail address or if linkedin account link.

**Comment by sentrionic** [comment] 2021-04-05 17:11
What problem did you encounter during the process? We can talk about it here for others to see that might have similar problems.

**Comment by dude83759** [comment] 2021-04-05 18:50
Not any specific problem. Actually I am a beginner so I am not much experienced with all this stuff. So I required detailed steps to clone your repo and achieve discord clone. Also will this discord clone chat work on a PHP website. If possible please connect on dude83759@gmail.com

**Comment by dude83759** [comment] 2021-04-05 18:52
I didn't tried installing this clone and working on it, should I do as defined in readme and also is AWS a must for uploading files or there is some free service for that or how to do that on localhost.

**Comment by sentrionic** [comment] 2021-04-05 19:42
You should follow the steps in the readme. If you don't have NodeJS yet, you should install that as well. You could replace the `yarn` command with `npm` in that case. 

AWS is required for file upload. You can definitely replace it with something like https://cloudinary.com/, though you would have to change the file upload part yourself in that case.

I don't know what you mean with a PHP website so I can't help you with that.

**Comment by dude83759** [comment] 2021-04-05 20:00
Thanks a ton for your reply. Okay, I will follow the steps in the readme and reach out to you for any queries. I would have been glad if I can contact you somewhere else because here it might be that you are not always active on Github. 
.....
Coming to NodeJS I have to installed it earlier for another project and so should I replace yarn commands with npm and will they work. Actually for what is yarn command used?

With PHP website I meant that I made a dynamic website with PHP for a project where users can login, so after that they can chat (like discord). 

So will this be totally seperate or how will I integrate that users database for login into chat with this one.

**Comment by dude83759** [comment] 2021-04-05 20:01
Also do you have any experience with WebRTC? Looking forward to hearing from you soon!

**Comment by sentrionic** [comment] 2021-04-05 20:08
[Yarn](https://classic.yarnpkg.com/lang/en/) is a dependency manager similar to npm.

The frontend and backend are separate entities, so you could use a different frontend or backend.  You would just have to call the endpoints listed on `localhost:4000/api`. I've never used PHP so I can't help you any further with that.
Similarly I haven't used WebRTC either.

**Comment by dude83759** [comment] 2021-04-05 20:24
Okay, I will try to do my best, if I encounter any error, would ask you.

**Comment by dude83759** [comment] 2021-04-05 20:26
Just one more thing, is your repo up to date with your demo website https://valkyrieapp.xyz/

**Comment by dude83759** [comment] 2021-04-05 20:41
Also sir, it is given that redis is not available officially for windows.

**Comment by sentrionic** [comment] 2021-04-05 20:41
Yes

**Comment by dude83759** [comment] 2021-04-05 20:42
you responded - Yes for which question ?

**Comment by sentrionic** [comment] 2021-04-05 20:44
The live version is up to date with the repository. As for Redis you would need to search for different solutions to run it on Windows, for example by using Docker.

**Comment by dude83759** [comment] 2021-04-05 20:45
> The live version is up to date with the repository. As for Redis you would need to search for different solutions to run it on Windows, for example by using Docker.

Okay

**Comment by dude83759** [comment] 2021-04-05 20:46
What about this https://redislabs.com/blog/redis-on-windows-10/

**Comment by dude83759** [comment] 2021-04-05 20:50
Also would this work for your repo https://divyanshushekhar.com/how-to-install-redis-on-windows-10/

**Comment by sentrionic** [comment] 2021-04-05 20:57
You can give both s shot, I would try the first one since it's provided by the redis devs themselves.

**Comment by dude83759** [comment] 2021-04-05 21:08
Okay, then I will try the 1st one and let you know.

> You can give both a shot, I would try the first one since it's provided by the redis devs themselves.

**Comment by dude83759** [comment] 2021-04-05 21:17
Just asking for a personal choice, won't the first option be difficult and take too much time than the second. If the results will be the same I would go for 2nd. What do you say?

**Comment by dude83759** [comment] 2021-04-05 21:32
I am going with WSL 1 because WSL 2 seems to be lengthy and tougher than WSL 1

**Comment by dude83759** [comment] 2021-04-05 22:24
How to get these values --- 

DATABASE_URL="postgresql://<username>:<password>@localhost:5432/db_name"
  REDIS_URL=localhost:6379
  CORS_ORIGIN=http://localhost:3000
  SECRET=SUPERSECRET
  REDIS_HOST=192.168.2.123
  REDIS_PORT=6379
  REDIS_PASSWORD=password

**Comment by dude83759** [comment] 2021-04-06 05:11
Hello Sir, 

Here is what I did but still the project is not working on my localhost.

- I installed postgresql and created a new db by command` create database databasename;` in psql.
- Installed redis on windows on WSL 1 as descirbed here https://redislabs.com/blog/redis-on-windows-10/
- installed yarn with `npm install --global yarn`
- run `yarn install` to install dependencies 
- Renamed .env.example to .env and fill in the values
- ```
DATABASE_URL="postgresql://<username>:<password>@localhost:5432/db_name" //here I entered my values
  REDIS_URL=localhost:6379
  CORS_ORIGIN=http://localhost:3000
  SECRET=SUPERSECRET
  REDIS_HOST=192.168.2.123
  REDIS_PORT=6379
  REDIS_PASSWORD=password
```
Didn't executed AWS part.

then on web 

- run `yarn install `

- copied .env from server to web

- run `yarn start `
- and went to localhost:3000 but nothing happened 
went to localhost:4000 ... home page of the project was visible but registration didn't worked.

Please help me troubleshoot, where did it went wrong.

**Comment by dude83759** [comment] 2021-04-06 05:44
Please help @sentrionic

**Comment by dude83759** [comment] 2021-04-06 06:29
@sentrionic Sir please reply I have tried everything but still it's not working.

**Comment by dude83759** [comment] 2021-04-06 06:49
in my server folder when I open cmd and run yarn start I get the error unable to connect the databse the server does not support ssl connections and tried all stackoverflow solutions but none worked for me, please help.

**Comment by sentrionic** [comment] 2021-04-06 07:37
There's not much help I can remote provide either. My only guess would be to remove
``` 
extra: {
  ssl: {
    rejectUnauthorized: false,
  },
},
ssl: true,
```
in database.ts

**Comment by dude83759** [comment] 2021-04-06 07:52
> There's not much help I can remote provide either. My only guess would be to remove
> 
> ```
> extra: {
>   ssl: {
>     rejectUnauthorized: false,
>   },
> },
> ssl: true,
> ```
> 
> in database.ts

Okay will try that but sir, I have been waiting for your reply for hours. Is there some communication method where we can have instant communication. Also if you agree I will be ready for a MS teams meeting or Google meet meeting.

**Comment by dude83759** [comment] 2021-04-06 08:05
Also @sentrionic as I mentioned what I did, did you find any other mistakes in what steps I followed, please let me know.

**Comment by sentrionic** [comment] 2021-04-06 08:17
Did you insert your postgres username and password in your `DATABASE_URL`?
The `REDIS_HOST` should be `localhost` as well, I made a mistake in the readme there while copying.

**Comment by dude83759** [comment] 2021-04-06 08:59
> Did you insert your postgres username and password in your `DATABASE_URL`?
> The `REDIS_HOST` should be `localhost` as well, I made a mistake in the readme there while copying.

Yes I inserted my username and password in DATABASE_URL in the .env file in server and copied that same file to web. 

also REDIS_HOST ==localhost 
just now removed this 
```
extra: {
  ssl: {
    rejectUnauthorized: false,
  },
},
ssl: true,
```
still getting the error below. 
![Screenshot (47)](https://user-images.githubusercontent.com/52997937/113686063-7f74c100-96e4-11eb-9a02-fa1c72a89f5f.png)

**Comment by sentrionic** [comment] 2021-04-06 09:11
Web uses a different `.env` file that should only contain `REACT_APP_API=http://localhost:4000`.
As I said previously remote help is very difficult. You could try to create a different node and express project
with TypeORM and see if you can connect to your database there.

**Comment by dude83759** [comment] 2021-04-06 09:14
Hey, thanks, finally I am not getting the error but still my localhost:3000 doesn't load anything and localhost:4000 does load like yours https://api.valkyrieapp.xyz/ and localhost:4000/ws loads same as yours https://api.valkyrieapp.xyz/ws/.

I am also having a nodejs application that runs on port 3000, so is that the cause of not loading localhost:3000

**Comment by sentrionic** [comment] 2021-04-06 09:20
If your client does not run on port 3000 then you need to change `CORS_ORIGIN` to the port it runs on.
What error do you get on your client?

**Comment by dude83759** [comment] 2021-04-06 09:47
Sir, I request you to please upload a step-by-step video guideline to make this project, please sir.

**Comment by dude83759** [comment] 2021-04-06 09:48
For beginners, it's too difficult too troubleshoot, by the way thanks a ton, you helped me with every error I encountered but still on localhost:4001 the application displays, I enter the details to register and when I click on register nothing happens.

**Comment by sentrionic** [comment] 2021-04-06 09:58
Beginners should probably follow tutorials first to get into React development with custom backends or try not to mess with the different ports too much.

If you press F12 you can open the developer console of your browser and then check if there are errors either in the console or network tab. If you run the server on a different port don't forget to change the `REACT_APP_API` to said port.

**Comment by dude83759** [comment] 2021-04-06 09:59
Sir, one very important request. It might take you some time but please please clone this repo yourself and do the steps again as you mentioned in the readme. then please let me know if you are able to install without any problem.

**Comment by dude83759** [comment] 2021-04-06 09:59
> Beginners should probably follow tutorials first to get into React development with custom backends or try not to mess with the different ports too much.
> 
> If you press F12 you can open the developer console of your browser and then check if there are errors either in the console or network tab. If you run the server on a different port don't forget to change the `REACT_APP_API` to said port.

Sure!

**Comment by dude83759** [comment] 2021-04-06 10:22
![Uploading Screenshot (49).png…]()

**Comment by sentrionic** [comment] 2021-04-06 11:01
You client runs on 4001 right? Your backend uses another port, that's the one that you need to specify in the env variable.

**Comment by dude83759** [comment] 2021-04-06 12:24
![Screenshot (50)](https://user-images.githubusercontent.com/52997937/113709982-c5d81900-9700-11eb-88e8-720aaaef69f1.png)
Now what to do???

values of server .env
PORT=3000
REDIS_URL=localhost:6379
CORS_ORIGIN=http://localhost:3000
SECRET=supersecret

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=


vlaue of web .env.development
browser=none
REACT_APP_API=http://localhost:3000

**Comment by dude83759** [comment] 2021-04-06 12:26
Now after this if I open localhost:3000 it opens swagger UI, if I open localhost:3000/ws/ it opens Valkyrie websockets. 

if I open 192.168.1.7:3000 it does open valkyrie but clicking on registration does nothing.

**Comment by dude83759** [comment] 2021-04-06 13:04
Hey, thanks a ton, finally I am able to register, login, create server, add users, make friends, notification system working, create channel (Private also), get notified about online/offline, get notified about who's typing in the channel. 

How can I add the option of user typing.... in direct messaging. Also user avatar didn't changed when I uploaded one and file upload didn't worked. 

is it that for both of them I will require AWS S3. 

Again, thanks a lot for this amazing project and helping me resolve all my enquiries, it's much appreciated would look to collaborate soon with you for this or any project in future. 

Now coming to how did I solved my error, I think it was already solved because when I was solving error for connection to database somehow i might have changed ports, now after changing correct ports for hours, being frustrated I saw ports for your git repo and changed them in mine local project and it worked.

**Comment by dude83759** [comment] 2021-04-06 13:09
when using the project on localhost couldn't I simply save images in the product folder, because I am not going to deploy this online so AWS S3 seems a 2nd option. Please let me know.

**Comment by sentrionic** [comment] 2021-04-06 14:13
You can store files to your local device and serve them yes. Since I have an AWS account I haven't used that option in a long time and therefore can't really remember how it worked.

As for user typing in DMs, that might be something I forgot to add.

**Comment by dude83759** [comment] 2021-04-06 17:50
Yeah, pardon me the user is typing ....  is working on both direct messages and channel messages on server.
Coming to storage I am going to try AWS and let you know what happens, do I just have to change 
AWS_ACCESS_KEY=ACCESS_KEY
  AWS_SECRET_ACCESS_KEY=SECRET_ACCESS_KEY
  AWS_STORAGE_BUCKET_NAME=STORAGE_BUCKET_NAME
  AWS_S3_REGION=S3_REGION
  GMAIL_USER=GMAIL_USER
  GMAIL_PASSWORD=GMAIL_PASSWORD
  
  also where we are having mails and why? 
  for OTP or what?
  Also, coming to removing a friend it works fine on your demo website but on my local storage I am able to remove friend from friends section but when I click friend on right side bar (where user are shows offline/online) it gives a error page but friend is removed please help me correct that.
  
  
  Also talking about what functions of the repo are wroking on localhost are ___

Message, Channel, Server CRUD --- yes
Authentication using Express Sessions --- don't know what exactly is this but seems yes (if possible please explain)
Channel / Websocket Member Protection --- don't know what exactly is this but seems yes (if possible please explain)
Realtime Events --- yes events like adding friend, message, crud operations happens in real time
File Upload (Avatar, Icon, Messages) to S3 -- going to try this
Direct Messaging - yes
Private Channels - yes
Friend System - yes
Notification System - yes (would like to get notified about channel messages like we get notified about direct messages)
Basic Moderation for the guild owner (delete messages, kick & ban members) -- yes
(Basically 2015 Discord features with 2021 Look) --- yes 

in all, it's a fantastic repo. 

Would you please help me add emoji part in the chat, would be glad to hear from you soon! 

Screenshots for remove friend error (by right clicking on the friend in the right side bar ) 
Unhandled Rejection (TypeError): Cannot read property 'filter' of undefined


![Screenshot (52)](https://user-images.githubusercontent.com/52997937/113756067-9dffaa00-972e-11eb-8273-51ca5ae129b1.png)
![Screenshot (51)](https://user-images.githubusercontent.com/52997937/113756074-9f30d700-972e-11eb-898e-94418afb764f.png)

**Comment by dude83759** [comment] 2021-04-06 18:21
For specific personalized conversation we may use https://gitter.im/ (login with GitHub).

**Comment by sentrionic** [comment] 2021-04-06 18:40
- Emails are for resetting passwords, if you aren't interested in that you can skip that.
- Express Sessions are a way to authenticate the user. If you have used JWT, sessions are similar to that.
- Channel/Websocket Protection means that non authenticated users and users that are not members of that guild/channel can't subscribe to those events.
- As for that error I will it out later.

As for new features I have currently no interest in adding new stuff. If you want emoji take a look at [Emoji Mart](https://github.com/missive/emoji-mart).
The only reason I didn't add it is that if I want to create a mobile app I can't use those emotes.

**Comment by dude83759** [comment] 2021-04-06 19:20
> * Emails are for resetting passwords, if you aren't interested in that you can skip that.
> * Express Sessions are a way to authenticate the user. If you have used JWT, sessions are similar to that.
> * Channel/Websocket Protection means that non authenticated users and users that are not members of that guild/channel can't subscribe to those events.
> * As for that error I will it out later.
> 
> As for new features I have currently no interest in adding new stuff. If you want emoji take a look at [Emoji Mart](https://github.com/missive/emoji-mart).
> The only reason I didn't add it is that if I want to create a mobile app I can't use those emotes.

Thanks!

**Comment by dude83759** [comment] 2021-04-06 19:23
If I am not disturbing you then will you please take some time out from your schedule tasks for the following. 

I have a mini web app which already has a login/register (DB used --> MySQL).

Now I want to integrate this chat on that mini web-app. 

I want that if I login & click on chat option this discord chat opens for that registered user without asking again for the username and password for both login and register.

Will I have to connect mysql and postgresql and fetch table entries from 1st to 2nd and while clicking on chat run an api to take values for user log-in automatically.

**Comment by sentrionic** [comment] 2021-04-06 19:54
That is out of scope of my knowledge, all my projects have been monolithic using the same database and Redis instances.

**Comment by dude83759** [comment] 2021-04-06 20:09
> That is out of scope of my knowledge, all my projects have been monolithic using the same database and Redis instances.

Okay, no problem.

**Comment by dude83759** [comment] 2021-04-06 20:17
How are you handling register/login in this, I mean what files should I look for?

**Comment by dude83759** [comment] 2021-04-06 20:19
Also please tell about file upload using cloudinary, what files would I have to change?

**Comment by sentrionic** [comment] 2021-04-06 20:38
Authentication is in the user directory on the server side and `auth.ts` on the client side. You would have to change stuff in `fileUtils.ts` to replace AWS with Cloudinary.

**Comment by dude83759** [comment] 2021-04-07 07:30
> Authentication is in the user directory on the server side and `auth.ts` on the client side. You would have to change stuff in `fileUtils.ts` to replace AWS with Cloudinary.

Okay, will try that.

**Comment by dude83759** [comment] 2021-04-08 13:29
Sir, please help me with file upload on localhost.

**Comment by sentrionic** [comment] 2021-04-08 14:32
Look into something like [that](https://www.techiediaries.com/nestjs-upload-serve-static-file/)

**Comment by dude83759** [comment] 2021-04-10 21:20
Hello Sir, how can I change the logo here, please tell me the file. 

![Screenshot (55)](https://user-images.githubusercontent.com/52997937/114284889-a6c6e780-9a70-11eb-9f98-17d4c19a37f6.png)

**Comment by itsbek** [comment] 2021-04-11 05:28
hey there, it's really awesome build!
NestJs is totally new world to me and Node itself at some point.

I have followed the steps in the Readme and deployed the backend to heroku and frontend to Netlify. Set all the AWS, postgres and redis credentials in the config vars in the Heroku side accordingly.
* But when I try to register it throws me back to the login page after registering successfully.
* login page takes me in for about 2 seconds and routes back to login page again. The error message on the console as follows:
![photo6312330598076754710](https://user-images.githubusercontent.com/65237794/114293348-c250e300-9aae-11eb-84fa-e08dfd61e960.jpg)

if my guess is right, redis is not caching sessionID and storing it in the cookies, right?
is that possible that, redis  add on heroku not connected properly? 

I  would appreciate your opinion and any guide on this. Also, planning to develop the build any further? like confirm email on register; signup via google/facebook/ etc? 

thanks  a lot, it was a great learning curve!

**Comment by itsbek** [comment] 2021-04-11 05:32
hey there, it's really awesome build!
NestJs is totally new world to me and Node itself at some point.

I have followed the steps in the Readme and deployed the backend to heroku and frontend to Netlify. Set all the AWS, postgres and redis credentials in the config vars in the Heroku side accordingly.

    But when I try to register it throws me back to the login page after registering successfully.
    login page takes me in for about 2 seconds and routes back to login page again. The error message on the console as follows:
   
![photo6312330598076754710](https://user-images.githubusercontent.com/65237794/114293621-2674a680-9ab1-11eb-9e6a-557dd8e4783e.jpg)


if my guess is right, redis is not caching sessionID and storing it in the cookies, right?
is that possible that, redis add on heroku not connected properly?

I would appreciate your opinion and any guide on this. Also, planning to develop the build any further? like confirm email on register; signup via google/facebook/ etc?

thanks a lot, it was a great learning curve!

**Comment by sentrionic** [comment] 2021-04-11 09:36
@dude83759 Check out [HomeIcon.tsx](https://github.com/sentrionic/Valkyrie/blob/45be277fd6270a6359151536dcb55a183e116cd3/web/src/components/sections/HomeIcon.tsx#L58). You will need to replace it with a SVG.

**Comment by sentrionic** [comment] 2021-04-11 09:39
@itsbek My first guess is that you aren't using the same domain name for your backend and frontend.
After login does the browser have the cookie set? You will also need to change the domain in `sessionmiddleware.ts `.

Currently no interest in adding any new features, I would be more interested in performance improvements first.

**Comment by itsbek** [comment] 2021-04-11 10:29
> @itsbek My first guess is that you aren't using the same domain name for your backend and frontend.
> After login does the browser have the cookie set? You will also need to change the domain in `sessionmiddleware.ts `.

- I've set domain in `sessionMiddleware` to my custom one
- could you please elaborate more on your 1st statement?

in the backend, heroku set the domain under the created app name. *ex. myapp.herokuapp.com*
and in the frontend(Netlify), I've set the *REACT_APP_API = myapp.herokuapp.com* accordingly

and finally, I have changed randomly generated domain name by Netlify to my own *ex. mycustomdomain.com* custom one ~ in the backend *CORS_ORIGIN = mycustomdomain.com*

**Comment by itsbek** [comment] 2021-04-11 10:41
> Currently no interest in adding any new features, I would be more interested in performance improvements first.

I loved the architecture and how clean the code is, I would be delighted to add some value on the build if I could! Although, it's smth new to me, I'm ready to take a chance and help you. of course under your guidance

**Comment by sentrionic** [comment] 2021-04-11 12:39
I believe a requirement for Express Sessions is that it has to use the same domain name, so your backend needs to have a variation of `mycustomdomain.com` as well.

I used [Ben Awad's ](https://youtu.be/I6ypD7qv3Z8?t=42235) video for the deployment, maybe it might help you as well.

As for checking if your cookie is set, I meant this:
![image](https://user-images.githubusercontent.com/38354571/114304417-41f0a900-9ad3-11eb-852f-9bb38171b556.png)

As for your other post, of course you can try adding features to your build. I'm currently working on a mobile app so every new feature means more work there as well. So until I'm done with the app I'm trying to keep new stuff to a minimum.

**Comment by itsbek** [comment] 2021-04-11 12:58
yeah I just noticed that i missed domain/subdomain step and also, my cookies are empty and I guess cuz of dns settings as well
thanks for the link on setting up the dns, I was just watching his [this
](https://www.youtube.com/watch?v=fWD_ciSWklQ)tutorial
![Screenshot from 2021-04-11 17-49-59](https://user-images.githubusercontent.com/65237794/114304789-80479180-9aee-11eb-9c68-dfad8f162346.png)

great, if you're using React Native on that, I am here to help with anything I can

**Comment by sentrionic** [comment] 2021-04-11 13:10
I'm actually using Flutter for the app since I prefer the UI Kit and DX there and it seems to have some more jobs here.
I do know that using React Native would have allowed me to reuse a lot of the logic.

**Comment by dude83759** [comment] 2021-04-11 13:48
@sentrionic Sir, you have always been very helpful with all my queries, I would request you if possible and if your schedule time allows you to get some free time to add instructions on how to use file upload on localhost.

**Comment by itsbek** [comment] 2021-04-11 14:13
> I'm actually using Flutter for the app since I prefer the UI Kit and DX there and it seems to have some more jobs here.
> I do know that using React Native would have allowed me to reuse a lot of the logic.

cool, all the best! will definitely check that out

**Comment by dude83759** [comment] 2021-04-11 14:15
@itsbek did you tried serving files on localhost, would like to know that?

**Comment by itsbek** [comment] 2021-04-11 14:18
I have changed the dns settings, however need to wait till it propagates... perhaps, I am still missing something on dns configuration.
could you run on setting the dns in your case please? If I'm not mistaken you have used Netlify, Heroku and Namecheap is in your build too right?

**Comment by itsbek** [comment] 2021-04-11 14:19
@dude83759 what do you mean?

**Comment by dude83759** [comment] 2021-04-11 14:23
> @dude83759 what do you mean?

Hey, I mean that how are you using file upload feature of the chat, probably AWS... I am looking to upload files to localhost and display them by localhost itself.

**Comment by itsbek** [comment] 2021-04-11 14:34
ahh that one, that feature is disabled - if I am not mistaken to avoid spam which would also cost for storing in S3 but that's only in production. so if you running the start:prod then you need to enable it. remove the disable variable in the web>components>layouts>guilds>chat

but setting up the local storage is not clear to me cuz I didn't dig up on that, just google it and you need to replace the aws S3 paths with your local storage

**Comment by sentrionic** [comment] 2021-04-11 14:37
My current DNS are:
Namecheap:
![namecheap](https://user-images.githubusercontent.com/38354571/114308384-08746980-9ae4-11eb-9f6d-b1b3c960cb87.png)

Heroku:
![heroku](https://user-images.githubusercontent.com/38354571/114308397-1d50fd00-9ae4-11eb-91ac-e5dcf2ff4564.png)

I'm using a paid version of Heroku so I also get the ssl, maybe you are missing that.

**Comment by itsbek** [comment] 2021-04-11 14:41
right! that should be the cause.
hobby tier will do the job?

**Comment by sentrionic** [comment] 2021-04-11 14:47
I'm using hobby tier yes.
You could also try setting Cloudflare in front of the backend to get free ssl, but I'm not sure if that will work with the sessions.

**Comment by itsbek** [comment] 2021-04-11 15:10
that's fine I just upgraded to hobby tier as well
but is it possible to get ip address of an app in netlify? I thought we can't according to [this](https://answers.netlify.com/t/get-my-netlify-apps-ip-address/18417)

**Comment by itsbek** [comment] 2021-04-11 15:19
just upgraded to hobby tier as well, but netlify app has an ip address?

**Comment by sentrionic** [comment] 2021-04-11 15:39
It does, I think it's in the domain settings. It should have one like it's shown in Ben's video with Vercel.

**Comment by itsbek** [comment] 2021-04-11 15:43
looked up for [it](https://answers.netlify.com/t/get-my-netlify-apps-ip-address/18417/3), apparently it's Netlify’s load balancer IP address 104.198.14.52 
however, it's different in the current [apex domain](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-an-apex-domain)
shall I set it to the `104.198.14.52`  or `75.2.60.5`, that's interesting...

**Comment by sentrionic** [comment] 2021-04-11 15:59
I actually can't remember all the steps I took I'm afraid.
I would try it with the `104.198.14.52` option since it's the one I'm currently using.

**Comment by itsbek** [comment] 2021-04-11 16:10
my dns settings and status are just like yours all over the platforms - to my own addresses of course
however, the site is insecure when opened
I suppose I need only to wait now...

**Comment by sentrionic** [comment] 2021-04-11 16:15
You can use something like https://dnschecker.org/. If most can't resolve it then there's an error.

**Comment by itsbek** [comment] 2021-04-11 16:56
all passed but Im still being redirected to login page. here, check it out yourself testdeploymyapp.xyz

**Comment by itsbek** [comment] 2021-04-11 17:03
still receiving 403 forbidden status, sighs...

**Comment by itsbek** [comment] 2021-04-11 17:10
> Heroku:
> ![heroku](https://user-images.githubusercontent.com/38354571/114308397-1d50fd00-9ae4-11eb-91ac-e5dcf2ff4564.png)

just wanted to ask why did you add _api_ in front of your domain? I did the same too, but just followed yours that's why...

**Comment by itsbek** [comment] 2021-04-11 17:14
I have noticed in your website, cookies are there even in the initial load, but mine is empty always...
> ![Screenshot from 2021-04-11 17-49-59](https://user-images.githubusercontent.com/65237794/114304789-80479180-9aee-11eb-9c68-dfad8f162346.png)

**Comment by sentrionic** [comment] 2021-04-11 17:25
The api part is for the backend and it's something I took from Ben.
As for your cookies still not being set, I got no idea, since trust proxy is set and your changed your domain.

**Comment by itsbek** [comment] 2021-04-11 17:28
what do you think I should do? if it's possible and alright with you I can live share on the vscode for quick scan

**Comment by itsbek** [comment] 2021-04-11 17:53
is that possible that, dns settings still haven't been applied yet or smth similar?

**Comment by sentrionic** [comment] 2021-04-11 18:03
Since you set your domain in the middleware and your backend in the web environment variables, I really don't have anything else I could point you to. All I can do is show you my netlify settings:
![image](https://user-images.githubusercontent.com/38354571/114315806-d8878f00-9b00-11eb-806d-b9d4967f57b7.png)

**Comment by itsbek** [comment] 2021-04-11 18:14
yeak my netlify is the same too, Im gonna try to dig up more 
if you have anything in mind plz feel free to share, and thank you!

**Comment by itsbek** [comment] 2021-04-12 01:38
Heyyy, I woku up and visited the deploy page and to my surprisemy deploy is up and running 😀 
Just wanted to ask did I say it right about uploading the files? if not, how shall I approach it?

> ahh that one, that feature is disabled - if I am not mistaken to avoid spam which would also cost for storing in S3 but that's only in production. so if you running the start:prod then you need to enable it. remove the disable variable in the web>components>layouts>guilds>chat

**Comment by sentrionic** [comment] 2021-04-12 05:59
You are right with that and you would have to remove the check on the backend as well.
Editing Messages was fixed in the latest commit.
AWS policies you best google I don't think my settings are the recommended ones.

**Comment by itsbek** [comment] 2021-04-12 06:22
check in the backend? 
ooh I see, if I'll try the last commit then, but if I am not mistake I pulled your last month commit, who knows I'll try again
and abt aws policies - I'm not intending to make it as identical as yours, but just was wondering which/what feature/policy allows to get back avatar images

**Comment by sentrionic** [comment] 2021-04-12 07:41
The `createMessage` function has a `if (file && !PRODUCTION)` check, you will need to remove the `!PRODUCTION` part.

My bucket has the following policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::harmony-cdn/files/*"
        }
    ]
}
```

**Comment by itsbek** [comment] 2021-04-12 09:04
I have just pulled your latest commit, and deployed it but had these on the logs:
![Screenshot from 2021-04-12 13-59-17](https://user-images.githubusercontent.com/65237794/114369605-feac3e00-9b97-11eb-9905-9cfae9922808.png)

**Comment by sentrionic** [comment] 2021-04-12 09:59
I would just clear the database, Heroku has that option if you go to
Resources > Heroku Postgres > Settings > Reset DB
Since my production build doesn't really host actual important stuff I don't pay too much attention to database migrations.

**Comment by itsbek** [comment] 2021-04-12 10:11
yep I did try that, but 
*(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection* error being pain

**Comment by itsbek** [comment] 2021-04-12 10:26
I have taken off the` !PRODUCTION` part in the backend and `disabled={!disable}` in the frontend part but somehow the file upload  icon doesn't seem to respond. 
![Screenshot from 2021-04-12 15-17-40](https://user-images.githubusercontent.com/65237794/114379868-cd853b00-9ba2-11eb-87e6-08ed21c4a3fc.png)

should I try to remove `hidden` in the `input`
![Screenshot from 2021-04-12 15-25-16](https://user-images.githubusercontent.com/65237794/114380397-7c297b80-9ba3-11eb-82f1-b18ff8c2e9c4.png)

**Comment by sentrionic** [comment] 2021-04-12 10:49
I think the disable check should be the one that blocked it.

**Comment by itsbek** [comment] 2021-04-12 10:51
yep, tried removing that too
if you meant `disabled={isSubmitting || disable}`

**Comment by itsbek** [comment] 2021-04-12 10:51
it uploads the file to s3 but doesn't display it in chat

**Comment by sentrionic** [comment] 2021-04-12 11:08
You see the image in your browser if you follow the s3 link right? If not then that might be s3 perms.
You also used the new frontend right? Since I replaced the old url and file type with a new attachment entity.

**Comment by itsbek** [comment] 2021-04-12 11:12
:man_facepalming: nope
I used the old web with new server, will fix it now

**Comment by itsbek** [comment] 2021-04-14 08:41
good day @sentrionic I was thinking to add verification the profile with phone number, facebook, instagram and similar other social media platforms. how shall I approach it?

**Comment by sentrionic** [comment] 2021-04-14 13:03
You should probably look into Passport and its NestJS [implementation](https://docs.nestjs.com/security/authentication) for that. As I've only done email and password registration I can't help you further.
The important part is that in the end of the authentication you set your session with the user id.

**Comment by dude83759** [comment] 2021-04-21 11:58
Sir, how can I change the look, what files should I focus on?

**Comment by dude83759** [comment] 2021-04-21 20:35
> Sir, how can I change the look, what files should I focus on?

Sir, please tell me how can I change CSS, what files should I look for, also how can I make this repsonsive.

**Comment by dude83759** [comment] 2021-04-22 06:43
Sir can I use mysql instead of postgresql

**Comment by sentrionic** [comment] 2021-04-22 09:04
The client uses Chakra UI which uses css-in-js, so if you want to change colors you would have to change them in the compoenent using Chakra's props.
Same for [responsive design](https://chakra-ui.com/docs/features/responsive-styles).
You can use mysql, but you would have to adapt the raw sql queries since they use the postgresql format.

**Comment by dude83759** [comment] 2021-04-22 09:42
> The client uses Chakra UI which uses css-in-js, so if you want to change colors you would have to change them in the compoenent using Chakra's props.
> Same for [responsive design](https://chakra-ui.com/docs/features/responsive-styles).
> You can use mysql, but you would have to adapt the raw sql queries since they use the postgresql format.

Okay, thanks a ton.

**Comment by itsbek** [comment] 2021-04-25 05:01
Hello there @sentrionic I was playing with UI and kinda can't figure out how to change the form transparency and input fields background color... Thanks in advance!
![Screenshot from 2021-04-25 09-57-18](https://user-images.githubusercontent.com/65237794/115981382-b3892680-a5ac-11eb-94ff-0da17062bdf3.png)

**Comment by ovitente** [comment] 2021-04-25 15:57
Hi
How many voice users it can handle in one voice channel, with mandatory push-to-talk mode?
I am teamspeak admin, and we would like to handle +1000 users. Is it possible?

**Closed** 2021-05-29 16:47 UTC
